### ISSUE TITLE
Loading circle and result text/Icon shows simultaneously

### ISSUE THREAD

**Issue by CXZ7720** [Taewan-P/MediChecker#11]
![KakaoTalk_20200323_191715452_02](https://user-images.githubusercontent.com/29659112/77307122-09512680-6d3c-11ea-8ecf-39be86298109.jpg)

While load a data from web, textview and Icon shows simultaneously.
It should prevent to show while loading circle running.

**Comment by mjkya** [comment]
<img width="394" alt="스크린샷 2020-03-25 오전 2 35 51" src="https://user-images.githubusercontent.com/39973760/77458345-64207600-6e41-11ea-8650-727806bc322e.png">

fixed it. #15
